version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source"
    schedule:
      interval: "weekly"
    groups:
       Roslynator:
          applies-to: version-updates
          patterns:
            - "Roslynator*"
      
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
