name: code coverage

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/CodeCoverage.yml'
      - 'source/**'

jobs:
  code_coverage:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: Collect coverage
      run: dotnet test source -c Release --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml

    - name: Upload to coverall
      uses: coverallsapp/github-action@v2
      with:
        file: TestResults\coverage.cobertura.xml
