name: Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ContinuousIntegration.yml'
      - 'source/DefaultCSharp/**'
      - 'source/Directory.Build.props'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        source-url: https://nuget.pkg.github.com/Doraku/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Run tests
      run: dotnet test source -c Release
      env:
        TEST: true

    - name: Decrypte snk file
      env:
        SNK_KEY: ${{ secrets.SNK_KEY }}
      run: gpg --quiet --batch --yes --decrypt --passphrase="$env:SNK_KEY" --output ds.snk ds.snk.gpg

    - name: Create package
      run: dotnet pack source -c Release -o build /p:Version=0-ci$(date +'%Y%m%d%H%M%S') /p:SignAssembly=true

    - name: Publish package
      run: dotnet nuget push build\*.nupkg
