name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ContinuousIntegration.yml'
      - 'source/DefaultCSharp/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Decrypte snk file
      env:
        SNK_KEY: ${{ secrets.SNK_KEY }}
      run: gpg --quiet --batch --yes --decrypt --passphrase="$env:SNK_KEY" --output ds.snk ds.snk.gpg

    - name: Create package
      run: dotnet pack source -c Release -o build /p:CI_VERSION=true

    - name: Publish package
      run: dotnet nuget push build\*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Doraku/index.json
